### ISSUE TITLE
import reference databases created using obitools3

### ISSUE THREAD

**Issue by slambrechts** [metabarcoding/obitools4#1]
Hi,

I exported the reference databases I created in obitools3 using:

```
obi export Coll/Coll01_db_97 --tab-output --print-na -o Coll01_db_97_EMBL

obi export Coll/Coll01_db_97 --fasta-output --print-na -o Coll01_db_97_EMBL.fasta
```

Can I use these in obitools4? And if so, how should I import them? Or should I export them differently?

Best,
Sam

**Comment by coissac** [comment]
THi,

The only problem you will have using this fasta is the taxid slot which is in upper case in the OBITool3 fasta file. But using `obiannotate` you can rename it easily:

```bash
obiannotate -R  taxid=TAXID Coll01_db_97_EMBL.fasta > Coll01_db_97_EMBL_obi4.fasta
````
